Controllers films users
DmitriiLebedev/java-filmorate pull request #3
Opened 2023-03-27 18:19 UTC by DmitriiLebedev

initial

2023-03-28 13:37 UTC, ErkinKasymaliev requested changes
привет, отличная работа!
Оставил 1 комменты

2023-03-28 13:37 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validation/After1895.java
> +public @interface After1895 {
отлично что сделали свою аннотацию!
но название неудачное, попробуйте DateValidator

2023-03-29 10:33 UTC, DmitriiLebedev commented
Переименовал в DateValidator, изначально я именовал в After1895 только по тому что валидатор под специфичную дату и если потом потребуется аналогичный, это может усложнить чтение кода

2023-03-29 11:10 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-13 05:11 UTC, merged