ТЗ 10
DmitriiLebedev/java-filmorate pull request #5
Opened 2023-04-13 05:18 UTC by DmitriiLebedev

initial

2023-04-13 14:12 UTC, ErkinKasymaliev requested changes
привет, хорошая работа
оставил комменты

2023-04-13 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film putFilm(Film film) {
лучше addFilm

2023-04-13 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private final Set<Film> filmsTreeSet = new TreeSet<>(Comparator.comparing(Film::getUsersSize).
если вам нужна сортировка, то удалите это и вместо HashMap используйте TreeMap выше

2023-04-13 14:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new FilmNotFoundException("Can't get film with id " + id);
все эти проверки надо в сервисах проводить, здесь просто обращение к хранилищу

2023-04-13 21:29 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private final Set<Film> filmsTreeSet = new TreeSet<>(Comparator.comparing(Film::getUsersSize).
В новом коммите вовсе снес сет, добавлять его было такое себе решение), сортировку сделал в методе

2023-04-14 05:05 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-25 19:17 UTC, merged