Add database
DmitriiLebedev/java-filmorate pull request #7
Opened 2023-05-09 20:06 UTC by DmitriiLebedev

initial

2023-05-10 06:32 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
Также не надо было удалять старые имплементации сервисов - InMemoryUserStorage и другие. У вас должно было быть InMemory.. и Db.. а в инжектить вы должны были их, используя @Primary или @Qualifier

2023-05-10 06:32 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    .mpa(new Mpa(filmRows.getInt("mpa_id")))
лучше перепишите запрос выше, используя join c таблицей Mpa. Так вы сразу получите и id и name mpa

2023-05-10 06:32 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public List<Integer> findAllFilms() {
надо возвращать List<Film>

2023-05-10 06:32 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FriendsDbStorage.java
> +        return jdbcTemplate.query("SELECT * FROM users WHERE user_id IN (SELECT friend_id AS id FROM friends" +
лучше перепишите через join

2023-05-10 06:32 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public List<Integer> findPopular(int count) {
надо возвращать List<Film>

2023-05-10 07:01 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public List<Integer> findPopular(int count) {
Привет, обязательно ли возвращать старые имплементации? Я снес их по совету других ребят, по тому что им ревьюеры говорили что они больше не нужны. Я конечно могу, но время до дедлайна крайне ограничено, сегодня будет свободных только пару часов, боюсь не успеть..

2023-05-10 07:04 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public List<Integer> findPopular(int count) {
хммм, ну хорошо, можешь не возвращать

2023-05-10 07:07 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public List<Integer> findPopular(int count) {
Спс, вечером тогда поправлю по комментам

2023-05-10 17:27 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public List<Integer> findAllFilms() {
Возвращать просто лист без параметров или лист фильмов?

2023-05-10 19:31 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    .mpa(mpaDbStorage.getMpaById(filmRows.getInt("mpa_id")))
Тут я разве что сам запрос не переписывал, а использовал соответствующий метод, в остальном по комментам

2023-05-11 04:50 UTC, ErkinKasymaliev requested changes
привет, оставил коммент

2023-05-11 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    .mpa(mpaDbStorage.getMpaById(filmRows.getInt("mpa_id")))
представим, что у вас 1 млн фильмов вернет запрос с 85 строки, тогда у вас будет еще 1 млн запрос чтобы вытащить mpa, поэтому запрос в 85 строке перепишите через join. Также поправьте для метода findFilmById

2023-05-11 05:11 UTC, DmitriiLebedev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    .mpa(mpaDbStorage.getMpaById(filmRows.getInt("mpa_id")))
Привет, поправлю в районе 20:00, успеем проверить?

2023-05-12 05:24 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
В следующий раз пиши сообщения в коммитах более подробно и на английском

2023-05-18 18:43 UTC, merged